name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    name: tests on CPU
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: pip
      - name: Install test dependencies
        run: pip install jupyter
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_PROGRESS_BAR: "on"
      - name: Run test
        run: jupyter nbconvert --debug --ExecutePreprocessor.timeout=None --ExecutePreprocessor.allow_errors=False --to notebook --inplace --execute stable_diffusion_notebookui.ipynb && echo "Success"
        env:
          PYTHONUNBUFFERED: "1"
          CUDA_VISIBLE_DEVICES: ""
      - name: Upload image outputs
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: outputs.zip
      - name: Upload notebook outputs
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: stable_diffusion_notebookui.ipynb
